### ISSUE TITLE
DashBoard, "RNA Search" bug

### ISSUE THREAD

**Issue by jkmarx** [refinery-platform/refinery-platform#1652]
Specific code commit: afe887dee960aa2e34837512072a6d7d6fd11304
Version of the web browser and OS: Version 56.0.2924.87 / 10.11.6
Environment where the error occurred (Vagrant VM and site conf mode or AWS instance):
https://test.stemcellcommons.org/#/

### Steps to reproduce
Please list all the actions and the input data used:

1. On the dashboard, search for RNA

### Observed behavior
![screen shot 2017-03-28 at 4 31 27 pm](https://cloud.githubusercontent.com/assets/9956764/24425992/13b1fc90-13d4-11e7-859c-d79f886bbb9a.png)

### Expected behavior
* Data set to display correct information

**Comment by scottx611x** [comment]
I can reproduce this error in: 
`Chrome Version 54.0.2840.59 (64-bit) & Firefox Version 52.0.1 (64-bit) in Ubuntu 16.04 LTS`
 on https://test.stemcellcommons.org/#/  afe887dee960aa2e34837512072a6d7d6fd11304

**Comment by ngehlenborg** [comment]
@flekschas: do you have any idea what might be happening here?

**Comment by flekschas** [comment]
@jkmarx @ngehlenborg what exactly is the issue?

**Comment by ngehlenborg** [comment]
See the screenshot. Some entries are missing the date - or is that expected?

**Comment by flekschas** [comment]
So the problem is the missing date information?

I would guess that Solr doesn't hold the date information and somehow the extra data is not pulled from the general API.

And this only happens with RNA search? What happens when you search for fibroblast? Without more information I can't say much.

**Comment by scottx611x** [comment]
@flekschas: Can reproduce with `fibroblast` as well
<img width="475" alt="screen shot 2017-04-10 at 3 27 13 pm" src="https://cloud.githubusercontent.com/assets/5629547/24878727/468937c2-1e02-11e7-8f42-8cbb815a98ce.png">

**Comment by flekschas** [comment]
Yeah looks like "Solr doesn't hold the date information and somehow the extra data is not pulled from the general API." since "10 T1/2 ..." now has a date attached. Quick solution is to store everything in Solr. Good solution is to refactor the search such that Django enriches search results with missing data on the server side before sending back the response to the frontend.

**Comment by jkmarx** [comment]
Fixed on beta as of 30567f8a2b1207f2e24fab92a744c151b64f88db

**Comment by scottx611x** [comment]
@jkmarx I'm still seeing the issue (Date information missing from some DataSets in the search results)

**Comment by jkmarx** [comment]
@scottx611x Sorry, I just looked at the issue and not the comments. The data sets returned are correct, didn't notice the missing date.

**Comment by jkmarx** [comment]
Related to #2760

**Comment by jkmarx** [comment]
@jkmarx Check if an issue on dashboard. Uses the same search API
